### ISSUE TITLE
Add explanation about permissions used to the README and website

### ISSUE THREAD

**Issue by IzzySoft** [ribbons/TaskerRsync#174]
My scanner got a few additional checks in January, and on today's update reported:

```
! repo/com.nerdoftheherd.tasker.rsync_280.apk declares sensitive permission(s):
  android.permission.MANAGE_EXTERNAL_STORAGE android.permission.REQUEST_INSTALL_PACKAGES
  android.permission.READ_EXTERNAL_STORAGE*
```

I got most permissions easily:

```yaml
    android.permission.MANAGE_EXTERNAL_STORAGE: needed to access files for sync
    android.permission.WRITE_EXTERNAL_STORAGE: needed to access files for sync
    android.permission.READ_EXTERNAL_STORAGE: needed to access files for sync
```

But what for is `REQUEST_INSTALL_PACKAGES` needed? Could you please clarify? Thanks in advance!
